[
  {
    admin_graphql_api_id: "gid://shopify/Product/8066269151460",
    body_html: "wear it",
    created_at: "2023-11-03T12:38:16+05:30",
    handle: "t-shirt",
    id: 8066269151460,
    product_type: "",
    published_at: "2023-11-03T12:38:16+05:30",
    template_suffix: "",
    title: "t-shirt",
    updated_at: "2023-11-03T12:38:16+05:30",
    vendor: "My Store",
    status: "active",
    published_scope: "global",
    tags: "",
    variants: [
      {
        admin_graphql_api_id: "gid://shopify/ProductVariant/44278071787748",
        barcode: "",
        compare_at_price: null,
        created_at: "2023-11-03T12:38:16+05:30",
        fulfillment_service: "manual",
        id: 44278071787748,
        inventory_management: "shopify",
        inventory_policy: "deny",
        position: 1,
        price: "0.00",
        product_id: 8066269151460,
        sku: "",
        taxable: true,
        title: "Default Title",
        updated_at: "2023-11-03T12:38:16+05:30",
        option1: "Default Title",
        option2: null,
        option3: null,
        grams: 1000,
        image_id: null,
        weight: 1,
        weight_unit: "kg",
        inventory_item_id: 46377847685348,
        inventory_quantity: 0,
        old_inventory_quantity: 0,
        requires_shipping: true,
      },
    ],
    options: [
      {
        name: "Title",
        id: 10260232601828,
        product_id: 8066269151460,
        position: 1,
        values: ["Default Title"],
      },
    ],
    images: [],
    image: null,
  },
];

// order
// {
//     id: 5417150447844,
//     admin_graphql_api_id: 'gid://shopify/Order/5417150447844',
//     app_id: 580111,
//     browser_ip: '117.211.48.162',
//     buyer_accepts_marketing: false,
//     cancel_reason: null,
//     cancelled_at: null,
//     cart_token: 'c1-130da51b60407c3f2f85de54de1eff90',
//     checkout_id: 34060023628004,
//     checkout_token: '3854d21d0924546bde07f44149a7cffc',
//     client_details: {
//       accept_language: 'en-IN',
//       browser_height: null,
//       browser_ip: '117.211.48.162',
//       browser_width: null,
//       session_hash: null,
//       user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36'
//     },
//     closed_at: null,
//     confirmation_number: '9X71FYTDE',
//     confirmed: true,
//     contact_email: 'simantaray0@gmail.com',
//     created_at: '2023-11-04T09:41:26+05:30',
//     currency: 'INR',
//     current_subtotal_price: '10000.00',
//     current_subtotal_price_set: {
//       shop_money: { amount: '10000.00', currency_code: 'INR' },
//       presentment_money: { amount: '10000.00', currency_code: 'INR' }
//     },
//     current_total_additional_fees_set: null,
//     current_total_discounts: '0.00',
//     current_total_discounts_set: {
//       shop_money: { amount: '0.00', currency_code: 'INR' },
//       presentment_money: { amount: '0.00', currency_code: 'INR' }
//     },
//     current_total_duties_set: null,
//     current_total_price: '11800.00',
//     current_total_price_set: {
//       shop_money: { amount: '11800.00', currency_code: 'INR' },
//       presentment_money: { amount: '11800.00', currency_code: 'INR' }
//     },
//     current_total_tax: '1800.00',
//     current_total_tax_set: {
//       shop_money: { amount: '1800.00', currency_code: 'INR' },
//       presentment_money: { amount: '1800.00', currency_code: 'INR' }
//     },
//     customer_locale: 'en-IN',
//     device_id: null,
//     discount_codes: [],
//     email: 'simantaray0@gmail.com',
//     estimated_taxes: false,
//     financial_status: 'paid',
//     fulfillment_status: null,
//     landing_site: '/',
//     landing_site_ref: null,
//     location_id: null,
//     merchant_of_record_app_id: null,
//     name: '#1001',
//     note: null,
//     note_attributes: [],
//     number: 1,
//     order_number: 1001,
//     order_status_url: 'https://0fe234-3.myshopify.com/66941092068/orders/17c59d9e08b0d5e8382d8bfba2f855be/authenticate?key=62811752ccd4e59e99c04a29ebc267f3',
//     original_total_additional_fees_set: null,
//     original_total_duties_set: null,
//     payment_gateway_names: [ 'bogus' ],
//     phone: null,
//     po_number: null,
//     presentment_currency: 'INR',
//     processed_at: '2023-11-04T09:41:25+05:30',
//     reference: '1e5153ff966f95745860e9db323dcd42',
//     referring_site: '',
//     source_identifier: '1e5153ff966f95745860e9db323dcd42',
//     source_name: 'web',
//     source_url: null,
//     subtotal_price: '10000.00',
//     subtotal_price_set: {
//       shop_money: { amount: '10000.00', currency_code: 'INR' },
//       presentment_money: { amount: '10000.00', currency_code: 'INR' }
//     },
//     tags: '',
//     tax_exempt: false,
//     tax_lines: [
//       {
//         price: '1800.00',
//         rate: 0.18,
//         title: 'IGST',
//         price_set: [Object],
//         channel_liable: false
//       }
//     ],
//     taxes_included: false,
//     test: true,
//     token: '17c59d9e08b0d5e8382d8bfba2f855be',
//     total_discounts: '0.00',
//     total_discounts_set: {
//       shop_money: { amount: '0.00', currency_code: 'INR' },
//       presentment_money: { amount: '0.00', currency_code: 'INR' }
//     },
//     total_line_items_price: '10000.00',
//     total_line_items_price_set: {
//       shop_money: { amount: '10000.00', currency_code: 'INR' },
//       presentment_money: { amount: '10000.00', currency_code: 'INR' }
//     },
//     total_outstanding: '0.00',
//     total_price: '11800.00',
//     total_price_set: {
//       shop_money: { amount: '11800.00', currency_code: 'INR' },
//       presentment_money: { amount: '11800.00', currency_code: 'INR' }
//     },
//     total_shipping_price_set: {
//       shop_money: { amount: '0.00', currency_code: 'INR' },
//       presentment_money: { amount: '0.00', currency_code: 'INR' }
//     },
//     total_tax: '1800.00',
//     total_tax_set: {
//       shop_money: { amount: '1800.00', currency_code: 'INR' },
//       presentment_money: { amount: '1800.00', currency_code: 'INR' }
//     },
//     total_tip_received: '0.00',
//     total_weight: 1000,
//     updated_at: '2023-11-04T09:41:28+05:30',
//     user_id: null,
//     billing_address: {
//       first_name: 'simanta',
//       address1: 'j',
//       phone: null,
//       city: 'guwahati',
//       zip: '783101',
//       province: 'Assam',
//       country: 'India',
//       last_name: 'Ray',
//       address2: null,
//       company: null,
//       latitude: null,
//       longitude: null,
//       name: 'simanta Ray',
//       country_code: 'IN',
//       province_code: 'AS'
//     },

//     customer: {
//       id: 6909957898468,
//       email: 'simantaray0@gmail.com',
//       accepts_marketing: false,
//       created_at: '2023-11-04T09:41:25+05:30',
//       updated_at: '2023-11-04T09:41:27+05:30',
//       first_name: 'simanta',
//       last_name: 'Ray',
//       state: 'disabled',
//       note: null,
//       verified_email: true,
//       multipass_identifier: null,
//       tax_exempt: false,
//       phone: null,
//       email_marketing_consent: {
//         state: 'not_subscribed',
//         opt_in_level: 'single_opt_in',
//         consent_updated_at: null
//       },
//       sms_marketing_consent: null,
//       tags: '',
//       currency: 'INR',
//       accepts_marketing_updated_at: '2023-11-04T09:41:25+05:30',
//       marketing_opt_in_level: null,
//       tax_exemptions: [],
//       admin_graphql_api_id: 'gid://shopify/Customer/6909957898468',
//       default_address: {
//         id: 8419005530340,
//         customer_id: 6909957898468,
//         first_name: 'simanta',
//         last_name: 'Ray',
//         company: null,
//         address1: 'j',
//         address2: null,
//         city: 'guwahati',
//         province: 'Assam',
//         country: 'India',
//         zip: '783101',
//         phone: null,
//         name: 'simanta Ray',
//         province_code: 'AS',
//         country_code: 'IN',
//         country_name: 'India',
//         default: true
//       }
//     },
//     discount_applications: [],
//     fulfillments: [],

//     line_items: [
//       {
//         id: 13456430039268,
//         admin_graphql_api_id: 'gid://shopify/LineItem/13456430039268',
//         attributed_staffs: [],
//         fulfillable_quantity: 1,
//         fulfillment_service: 'manual',
//         fulfillment_status: null,
//         gift_card: false,
//         grams: 1000,
//         name: 'Laptop',
//         price: '10000.00',
//         price_set: [Object],
//         product_exists: true,
//         product_id: 8066268823780,
//         properties: [],
//         quantity: 1,
//         requires_shipping: true,
//         sku: '',
//         taxable: true,
//         title: 'Laptop',
//         total_discount: '0.00',
//         total_discount_set: [Object],
//         variant_id: 44278070116580,
//         variant_inventory_management: 'shopify',
//         variant_title: null,
//         vendor: 'My Store',
//         tax_lines: [Array],
//         duties: [],
//         discount_allocations: []
//       }
//     ],
//     payment_terms: null,
//     refunds: [],
//     shipping_address: {
//       first_name: 'simanta',
//       address1: 'j',
//       phone: null,
//       city: 'guwahati',
//       zip: '783101',
//       province: 'Assam',
//       country: 'India',
//       last_name: 'Ray',
//       address2: null,
//       company: null,
//       latitude: 26.1585515,
//       longitude: 90.5446912,
//       name: 'simanta Ray',
//       country_code: 'IN',
//       province_code: 'AS'
//     },
//     shipping_lines: [
//       {
//         id: 4402629607652,
//         carrier_identifier: '650f1a14fa979ec5c74d063e968411d4',
//         code: 'Standard',
//         discounted_price: '0.00',
//         discounted_price_set: [Object],
//         phone: null,
//         price: '0.00',
//         price_set: [Object],
//         requested_fulfillment_service_id: null,
//         source: 'shopify',
//         title: 'Standard',
//         tax_lines: [],
//         discount_allocations: []
//       }
//     ]
//   }
